version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: film
      MYSQL_PASSWORD: film
      MYSQL_DATABASE: films
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local